### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by stevenmaguire** [idougherty/kangaroo-killer#1]
Great job @idougherty, @coolreader18, and the rest of the team! I think this turned out really cool, and funny! Sorry I was not able to attend the demo. I am glad that I was able to star the project and follow-along remotely after I left Saturday evening.

**Comment by idougherty** [comment]
Thanks! We really appreciated the guidance and help, we made sure to continue to have team discussions which was essential to keeping everything on track, as well as using git to make documents simple to update and work with.

**Comment by stevenmaguire** [comment]
@idougherty of course! I only wish I could've helped out a bit longer and seen the demo. What's next for the project? Going to keep it going?

**Comment by idougherty** [comment]
I just fixed some bugs with the system to kill people, now i think we're gonna work on balancing the game to make every building more useful and the end game much harder.

**Comment by coolreader18** [comment]
I'm down for doing that!
